// ─── Nutty Tales Crafts & Heritage / Clothing — Comprehensive Catalog ────────────
// Fall / Winter 2026: Kashmir to the World
// Real Luxury Fashion Ecommerce Data Model with Provenance, Variants, Sizes & Swatches

export type ClothingGender = 'women' | 'men' | 'kids' | 'unisex'

export type PrimaryClothingCategory =
  | 'women'
  | 'men'
  | 'kids'
  | 'shawls-stoles'
  | 'pherans'
  | 'jackets-coats'
  | 'winter-wear'
  | 'accessories'
  | 'heritage-home'

export type WarmthLevel = 'Light (12°C - 20°C)' | 'Medium (4°C - 12°C)' | 'Heavy (-10°C - 4°C)'

export interface ColorSwatch {
  name: string
  hex: string
  image?: string
}

export interface ProvenanceDetails {
  origin: string             // e.g. 'Kanihama, Budgam' or 'Downtown Srinagar'
  artisanGroup: string       // e.g. 'Master Artisan Cooperative Guild'
  craftTradition: string     // e.g. 'Tilla Zari Hand Needlework'
  material: string           // e.g. '100% Pure Australian Merino Wool'
  technique: string          // e.g. 'Hand-guided embroidery'
  artisanHours: number       // e.g. 160 hours
  giTagCertified: boolean
  giCertificateNo?: string
  care: string
}

export interface ReviewItem {
  id: string
  author: string
  city: string
  rating: number
  date: string
  comment: string
  verifiedPurchase: boolean
}

export interface ClothingProduct {
  id: string
  sku: string
  name: string
  slug: string
  gender: ClothingGender
  primaryCategory: PrimaryClothingCategory
  categoryLabel: string
  subCategory: string
  shortDesc: string
  longDesc: string
  editorialStory?: string
  price: number
  mrp: number
  image: string               // Image 1: Clean front studio shot on warm ivory
  secondaryImage: string      // Image 2: Back / reverse
  detailImage: string         // Image 3: Close-up of embroidery / material
  textureImage: string        // Image 4: Detail / texture
  packagingImage: string      // Image 5: Packaging / presentation box
  lifestyleImage?: string     // Image 6: Editorial / lifestyle shot
  processImage?: string       // Image 7: Verified artisan / loom process
  additionalImages: string[]
  sizes: string[]
  colorOptions: ColorSwatch[]
  material: string
  craft: string
  warmthRating: WarmthLevel
  length: 'Short' | 'Mid' | 'Long'
  occasion: 'Everyday' | 'Office' | 'Festive' | 'Wedding' | 'Luxury'
  fit: string
  dimensions: string
  provenance: ProvenanceDetails
  isNew: boolean
  isBestseller: boolean
  isFallWinter2026: boolean
  is3DSupported: boolean
  tryWithSiSupported: boolean
  stockStatus: 'IN_STOCK' | 'LOW_STOCK' | 'MADE_TO_ORDER'
  stockCount: number
  tags: string[]
  reviews: ReviewItem[]
  pairWithSlug?: string
}

// ─── THE FALL / WINTER 2026 CLOTHING CATALOG ─────────────────────────────────────
export const CLOTHING_PRODUCTS: ClothingProduct[] = [
  // ─────────────────────────────────────────────────────────────────────────────
  // 1. WOMEN'S PHERANS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'clt-wom-phr-001',
    sku: 'NT-FW26-WPHR-01',
    name: 'Imperial Zari Tilla Velvet Pheran',
    slug: 'imperial-zari-tilla-velvet-pheran',
    gender: 'women',
    primaryCategory: 'pherans',
    categoryLabel: 'Pherans',
    subCategory: 'Tilla / Zari Pherans',
    shortDesc: 'Deep Burgundy micro-velvet adorned with genuine metallic Tilla gold embroidery along the neck collar, vents and cuffs.',
    longDesc: `The pinnacle of royal Kashmiri winter couture. Crafted from plush, heavyweight micro-velvet with a silken drape, this pheran features authentic Tilla Dozi (metallic gold thread needlework). Master craftsmen meticulously weave real silver thread gilded in 24k gold through the neckline in the iconic Paisley and Chinar trellis.\n\nCut in the traditional relaxed Kashmiri silhouette, it allows graceful movement while providing impenetrable warmth during harsh winter evenings, wedding receptions, and gala occasions.`,
    editorialStory: 'Hand-embroidered over 80 hours by master Tilla artisans in Zadibal, Downtown Srinagar, following royal Mughal patterns.',
    price: 18500,
    mrp: 24500,
    image: '/images/crafts-pherans.jpg',
    secondaryImage: '/images/campaign-wear-the-story.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-pherans.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    lifestyleImage: '/images/campaign-wear-the-story.jpg',
    processImage: '/images/crafts-artisan-hands.jpg',
    additionalImages: [
      '/images/crafts-pherans.jpg',
      '/images/campaign-wear-the-story.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['S (38)', 'M (40)', 'L (42)', 'XL (44)', 'Free Size (Roomy)'],
    colorOptions: [
      { name: 'Imperial Burgundy', hex: '#631B26' },
      { name: 'Midnight Navy', hex: '#16223B' },
      { name: 'Deep Forest', hex: '#183B2B' },
      { name: 'Royal Onyx Black', hex: '#1A1A1A' },
    ],
    material: 'Heavy Silk Velvet (Silken drape with thermal lining)',
    craft: 'Tilla / Zari Hand Needlework (Pure metallic thread)',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Wedding',
    fit: 'Relaxed Traditional Kashmiri Silhouette',
    dimensions: 'Length: 46", Chest: 46", Shoulder: 17", Sleeve: 23"',
    provenance: {
      origin: 'Zadibal, Downtown Srinagar, Kashmir',
      artisanGroup: 'Mir Tilla Guild #12',
      craftTradition: 'Tilla Dozi (Silver-gilded metallic thread needlework)',
      material: 'Imported Heavy Silk Velvet with Satin Crepe Lining',
      technique: 'Pointed needle anchor stitch onto velvet canvas',
      artisanHours: 85,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-TILLA-2026-0412',
      care: 'Strictly dry clean only. Store folded inside breathable cotton garment bag.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 8,
    tags: ['pheran', 'women', 'velvet', 'tilla', 'zari', 'wedding', 'burgundy', 'fw26'],
    reviews: [
      {
        id: 'rev-001',
        author: 'Meenakshi Sundaram',
        city: 'New Delhi',
        rating: 5,
        date: 'Oct 2, 2026',
        comment: 'The weight of the velvet and the sheen of the Tilla thread are breathtaking. Wore it to a wedding in Srinagar and received endless compliments.',
        verifiedPurchase: true,
      },
      {
        id: 'rev-002',
        author: 'Ayesha Peerzada',
        city: 'Mumbai',
        rating: 5,
        date: 'Sep 28, 2026',
        comment: 'Pure elegance. The packaging box with the artisan card made it feel like receiving an heirloom.',
        verifiedPurchase: true,
      },
    ],
    pairWithSlug: 'royal-kani-pashmina-shawl-floral-jamawar',
  },
  {
    id: 'clt-wom-phr-002',
    sku: 'NT-FW26-WPHR-02',
    name: 'Kashmiri Pure Wool Aari Floral Pheran',
    slug: 'kashmiri-pure-wool-aari-floral-pheran',
    gender: 'women',
    primaryCategory: 'pherans',
    categoryLabel: 'Pherans',
    subCategory: 'Aari Pherans',
    shortDesc: 'Warm oatmeal wool woven in the Kashmir valley, embroidered with vibrant autumn leaves and wild flora in chain-stitch Aari work.',
    longDesc: `An essential wardrobe piece for crisp mountain winters and urban evenings alike. Made from pure local wool spun by cooperative weavers, this piece features elaborate Aari embroidery across the yoke, sleeves, and side slits.\n\nThe Aari hook creates delicate chain-stitch flowers inspired by the Shalimar and Nishat Mughal gardens. Lightweight yet deeply insulating, it can be styled effortlessly over winter trousers or churidars.`,
    editorialStory: 'Dyed with organic madder root and walnut bark extract to achieve warm, earthy autumn tones.',
    price: 9200,
    mrp: 12500,
    image: '/images/crafts-pherans.jpg',
    secondaryImage: '/images/crafts-artisan-hands.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-pherans.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    lifestyleImage: '/images/campaign-wear-the-story.jpg',
    processImage: '/images/crafts-artisan-hands.jpg',
    additionalImages: [
      '/images/crafts-pherans.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/campaign-wear-the-story.jpg',
    ],
    sizes: ['S (38)', 'M (40)', 'L (42)', 'XL (44)', 'Free Size'],
    colorOptions: [
      { name: 'Warm Oatmeal', hex: '#D8C7A5' },
      { name: 'Forest Moss', hex: '#2C4A3A' },
      { name: 'Rust Clay', hex: '#A34828' },
      { name: 'Charcoal Grey', hex: '#3D4146' },
    ],
    material: '100% Pure Kashmir Wool (Soft spun, non-scratch)',
    craft: 'Aari Hook Chain-Stitch Embroidery',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Everyday',
    fit: 'Comfort Regular Pheran Cut',
    dimensions: 'Length: 45", Chest: 44", Shoulder: 16.5", Sleeve: 22.5"',
    provenance: {
      origin: 'Charar-i-Sharief, Budgam, Kashmir',
      artisanGroup: 'Budgam Valley Craft Collective',
      craftTradition: 'Traditional Aari Needlework',
      material: '100% Natural Himalayan Sheep Wool',
      technique: 'Awl hook chain-stitch with woolen floss',
      artisanHours: 42,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-AARI-2026-0941',
      care: 'Dry clean recommended. Gentle hand wash in cold water with wool detergent permitted.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 15,
    tags: ['pheran', 'women', 'wool', 'aari', 'everyday', 'oatmeal', 'fw26'],
    reviews: [
      {
        id: 'rev-003',
        author: 'Dr. Neha Kapoor',
        city: 'Chandigarh',
        rating: 5,
        date: 'Oct 4, 2026',
        comment: 'So cozy and the chain stitch flowers are remarkably neat. The wool is gentle on sensitive skin.',
        verifiedPurchase: true,
      },
    ],
    pairWithSlug: 'heritage-sozni-embroidered-wool-stole',
  },
  {
    id: 'clt-wom-phr-003',
    sku: 'NT-FW26-WPHR-03',
    name: 'Contemporary Minimalist Cashmilon Pheran Set',
    slug: 'contemporary-minimalist-cashmilon-pheran-set',
    gender: 'women',
    primaryCategory: 'pherans',
    categoryLabel: 'Pherans',
    subCategory: 'Contemporary Pherans',
    shortDesc: 'Modernized mid-length Cashmilon pheran paired with matching straight-cut warm trousers. Subtle Sozni thread accents along the mandarin collar.',
    longDesc: `Designed for the modern professional seeking heritage warmth with contemporary office elegance. Made from premium Cashmilon blend that resists wrinkles and offers cloud-soft comfort.\n\nIncludes both the mid-thigh pheran tunic and coordinating tailored winter trousers with concealed side pockets and an elasticated waistband.`,
    price: 6800,
    mrp: 8900,
    image: '/images/crafts-pherans.jpg',
    secondaryImage: '/images/crafts-winterwear.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-pherans.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-pherans.jpg',
      '/images/crafts-winterwear.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['XS (36)', 'S (38)', 'M (40)', 'L (42)', 'XL (44)'],
    colorOptions: [
      { name: 'Camel Tan', hex: '#C19A6B' },
      { name: 'Slate Teal', hex: '#265961' },
      { name: 'Smoky Charcoal', hex: '#373A3C' },
    ],
    material: 'Cashmilon Acrylic-Wool Blend (Soft, anti-pilling, lightweight)',
    craft: 'Minimalist Sozni Needle Accents',
    warmthRating: 'Medium (4°C - 12°C)',
    length: 'Mid',
    occasion: 'Office',
    fit: 'Contemporary Straight Cut',
    dimensions: 'Top Length: 38", Bottom Length: 38", Chest: 42"',
    provenance: {
      origin: 'Nowhatta, Downtown Srinagar',
      artisanGroup: 'Shehjar Women Artisans Cooperative',
      craftTradition: 'Contemporary Needlework',
      material: 'Refined Cashmilon Blend',
      technique: 'Single-needle thread embroidery on cuffs and collar',
      artisanHours: 24,
      giTagCertified: false,
      care: 'Machine wash delicate cycle in cold water with mild detergent.',
    },
    isNew: true,
    isBestseller: false,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 18,
    tags: ['pheran', 'women', 'set', 'cashmilon', 'co-ord', 'office', 'contemporary'],
    reviews: [
      {
        id: 'rev-004',
        author: 'Ritu Sharma',
        city: 'Gurugram',
        rating: 5,
        date: 'Sep 29, 2026',
        comment: 'Perfect for working from home and chilly office boardrooms. Comfortable yet looks so put-together.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-wom-phr-004',
    sku: 'NT-FW26-WPHR-04',
    name: 'Heritage Sozni Silk-Floss Embroidered Pheran',
    slug: 'heritage-sozni-silk-floss-embroidered-pheran',
    gender: 'women',
    primaryCategory: 'pherans',
    categoryLabel: 'Pherans',
    subCategory: 'Sozni Pherans',
    shortDesc: 'Fine merino wool fabric enriched with microscopic Sozni needlework executed in pure mulberry silk floss. Subtle floral medallion design.',
    longDesc: `Sozni is renowned as the most delicate embroidery technique in the Himalayan subcontinent. Practiced with needles as fine as horsehair, the stitches are barely visible to the naked eye.\n\nThis piece presents floral medallions (Badam and Chinar motifs) scattered across the chest and borders, rendering a soft shimmering contrast against the rich woolen fabric.`,
    price: 14500,
    mrp: 18900,
    image: '/images/crafts-pherans.jpg',
    secondaryImage: '/images/crafts-shawls.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-pherans.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-pherans.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/campaign-wear-the-story.jpg',
    ],
    sizes: ['S (38)', 'M (40)', 'L (42)', 'XL (44)', 'Free Size'],
    colorOptions: [
      { name: 'Warm Ivory', hex: '#FAF5E8' },
      { name: 'Midnight Navy', hex: '#16223B' },
      { name: 'Mulberry Wine', hex: '#582138' },
    ],
    material: '100% Fine Merino Wool',
    craft: 'Fine Sozni Silk-Thread Needlework',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Festive',
    fit: 'Classic Relaxed Silhouette',
    dimensions: 'Length: 45", Chest: 45", Shoulder: 17", Sleeve: 23"',
    provenance: {
      origin: 'Pampore, Kashmir',
      artisanGroup: 'Saffron Valley Needle Guild',
      craftTradition: 'Traditional Sozni Needlework',
      material: 'Australian Merino Wool with Mulberry Silk Thread',
      technique: 'Double-sided micro needlework',
      artisanHours: 64,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-SOZNI-2026-0182',
      care: 'Dry clean only. Store wrapped in unbleached muslin.',
    },
    isNew: false,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 6,
    tags: ['pheran', 'women', 'sozni', 'wool', 'merino', 'festive', 'ivory', 'fw26'],
    reviews: [
      {
        id: 'rev-005',
        author: 'Shalini Verma',
        city: 'Bangalore',
        rating: 5,
        date: 'Sep 21, 2026',
        comment: 'The Sozni work is so refined it looks painted on. Truly heirloom craftsmanship.',
        verifiedPurchase: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 2. SHAWLS & STOLES (STANDALONE CATEGORY)
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'clt-shw-001',
    sku: 'NT-FW26-SHW-01',
    name: 'Royal Kani Pashmina Shawl (Floral Jamawar)',
    slug: 'royal-kani-pashmina-shawl-floral-jamawar',
    gender: 'unisex',
    primaryCategory: 'shawls-stoles',
    categoryLabel: 'Shawls & Stoles',
    subCategory: 'Pashmina',
    shortDesc: 'Centuries-old Kani loom masterpiece woven with wooden spools (tujis). Pure Changthangi Pashmina with rich Persian floral trellis.',
    longDesc: `The pinnacle of Kashmiri textile heritage. The Kani shawl is woven on traditional handlooms using tiny wooden eyeless bobbins called 'tujis', guided by coded poetic script known as 'Talim'. Every centimeter requires immense patience, taking two master artisans over 4 months to weave.\n\nCrafted from the gossamer underfleece of Himalayan Changthangi goats living at 14,000 feet, this shawl offers featherlight weight with incomparable warmth. An heirloom investment destined to be treasured across generations.`,
    editorialStory: 'Woven in the misty village of Kanihama, where looms have hummed rhythmically since the 15th-century Mughal court of Zain-ul-Abidin.',
    price: 38500,
    mrp: 49000,
    image: '/images/crafts-shawls.jpg',
    secondaryImage: '/images/crafts-artisan-hands.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-shawls.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    lifestyleImage: '/images/campaign-wear-the-story.jpg',
    processImage: '/images/crafts-artisan-hands.jpg',
    additionalImages: [
      '/images/crafts-shawls.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/crafts-winter-hero.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['Standard Wrap (200 cm × 100 cm)'],
    colorOptions: [
      { name: 'Crimson Jamawar', hex: '#631B26' },
      { name: 'Royal Ivory Gold', hex: '#EAE1CE' },
      { name: 'Midnight Navy', hex: '#16223B' },
      { name: 'Deep Emerald', hex: '#165B4C' },
    ],
    material: '100% Pure Changthangi Cashmere / Pashmina (14.5 Microns)',
    craft: 'Traditional Kani Weave (Talim System with Wooden Tujis)',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Luxury',
    fit: 'Draped Wrap',
    dimensions: '200 cm × 100 cm (80" × 40")',
    provenance: {
      origin: 'Kanihama Weavers Colony, Kashmir',
      artisanGroup: 'Kanihama Artisans Cooperative #14',
      craftTradition: 'Traditional Kani Weave (Talim System)',
      material: '100% Pure Changthangi Cashmere / Pashmina (14.5 Microns)',
      technique: 'Handloom with carved walnut tujis (wooden spools)',
      artisanHours: 320,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-KANI-2026-0891',
      care: 'Strictly professional dry clean. Store wrapped in pure unbleached muslin with natural cedar balls.',
    },
    isNew: false,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 4,
    tags: ['shawl', 'pashmina', 'kani', 'jamawar', 'gi-certified', 'luxury', 'heirloom', 'fw26'],
    reviews: [
      {
        id: 'rev-006',
        author: 'Geetika Oberoi',
        city: 'New Delhi',
        rating: 5,
        date: 'Sep 15, 2026',
        comment: 'An authentic Kani shawl is like wearing living history. Featherlight and astoundingly warm. The GI certification number gives genuine peace of mind.',
        verifiedPurchase: true,
      },
    ],
    pairWithSlug: 'imperial-zari-tilla-velvet-pheran',
  },
  {
    id: 'clt-shw-002',
    sku: 'NT-FW26-SHW-02',
    name: 'Fine Sozni Needle-Embroidered Pashmina Shawl (Hashi Border)',
    slug: 'fine-sozni-needle-embroidered-pashmina-shawl',
    gender: 'unisex',
    primaryCategory: 'shawls-stoles',
    categoryLabel: 'Shawls & Stoles',
    subCategory: 'Sozni',
    shortDesc: 'Pure hand-spun Pashmina with delicate Hashidar border embroidery in shaded silk floss. Minimalist elegance suited for formal evenings.',
    longDesc: `Where subtlety reigns supreme. While Jamawars blanket the fabric in embroidery, Hashidar shawls focus pure artisan skill into an enchanting 3-inch framing border around an unblemished natural cashmere body.\n\nHand-spun on traditional wooden charkhas and hand-woven in the Kashmir valley, this shawl drapes like liquid gossamer and easily passes through a signet ring.`,
    price: 24500,
    mrp: 32000,
    image: '/images/crafts-shawls.jpg',
    secondaryImage: '/images/crafts-stoles.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-shawls.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-shawls.jpg',
      '/images/crafts-stoles.jpg',
      '/images/crafts-artisan-hands.jpg',
    ],
    sizes: ['Standard Wrap (200 cm × 100 cm)'],
    colorOptions: [
      { name: 'Warm Camel', hex: '#C19A6B' },
      { name: 'Smoky Charcoal', hex: '#373A3C' },
      { name: 'Natural Natural Ivory', hex: '#F5EFE1' },
      { name: 'Rust Amber', hex: '#B85D36' },
    ],
    material: '100% Certified Pashmina (Pure Himalayan Cashmere)',
    craft: 'Fine Sozni Needle Embroidery (Hashidar border motif)',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Luxury',
    fit: 'Draped Wrap',
    dimensions: '200 cm × 100 cm (80" × 40")',
    provenance: {
      origin: 'Downtown Srinagar, Kashmir',
      artisanGroup: 'Bagh-e-Ali Weavers Society',
      craftTradition: 'Traditional Sozni Hand Needlework',
      material: '100% Changthangi Pashmina with Silk Floss Thread',
      technique: 'Single-needle satin stitch along framing border',
      artisanHours: 140,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-PASH-2026-1142',
      care: 'Strictly dry clean only. Wrap in muslin cloth.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 7,
    tags: ['shawl', 'pashmina', 'sozni', 'hashi', 'camel', 'ivory', 'minimalist', 'fw26'],
    reviews: [
      {
        id: 'rev-007',
        author: 'Arjun Mehra',
        city: 'London / Mumbai',
        rating: 5,
        date: 'Oct 1, 2026',
        comment: 'Understated luxury at its very best. The camel shade pairs effortlessly with both Nehru jackets and English overcoats.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-shw-003',
    sku: 'NT-FW26-SHW-03',
    name: 'Heritage Sozni Embroidered Wool Stole',
    slug: 'heritage-sozni-embroidered-wool-stole',
    gender: 'unisex',
    primaryCategory: 'shawls-stoles',
    categoryLabel: 'Shawls & Stoles',
    subCategory: 'Wool',
    shortDesc: 'Lightweight fine wool stole with subtle corner paisley (badam) needlework. Versatile for daily commutes, flights, and winter layering.',
    longDesc: `A practical yet deeply artisanal companion for everyday warmth. Woven from soft Australian-grade blended wool, this stole is sized for compact folding inside bags or effortless draping around the shoulders.\n\nCrafted with subtle four-corner needlework and finished with neat self-fringed edges.`,
    price: 4500,
    mrp: 6200,
    image: '/images/crafts-stoles.jpg',
    secondaryImage: '/images/crafts-shawls.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-stoles.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-stoles.jpg',
      '/images/crafts-shawls.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['Compact Stole (180 cm × 70 cm)'],
    colorOptions: [
      { name: 'Slate Teal', hex: '#1E585E' },
      { name: 'Oatmeal Beige', hex: '#D2C4A7' },
      { name: 'Burgundy Wine', hex: '#582138' },
      { name: 'Jet Black', hex: '#1C1C1C' },
    ],
    material: '100% Fine Himalayan Wool',
    craft: 'Corner Sozni Hand Needlework',
    warmthRating: 'Medium (4°C - 12°C)',
    length: 'Mid',
    occasion: 'Everyday',
    fit: 'Shoulder Drape / Scarf Wrap',
    dimensions: '180 cm × 70 cm (70" × 28")',
    provenance: {
      origin: 'Kupwara / Baramulla, Kashmir',
      artisanGroup: 'Northern Valley Weaving Collective',
      craftTradition: 'Traditional Wool Weave & Stitch',
      material: 'Fine Sheep Wool with Cotton Core',
      technique: 'Light hand needlework',
      artisanHours: 28,
      giTagCertified: false,
      care: 'Dry clean recommended or gentle cold hand wash.',
    },
    isNew: true,
    isBestseller: false,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 24,
    tags: ['stole', 'wool', 'sozni', 'everyday', 'teal', 'beige', 'unisex', 'travel'],
    reviews: [
      {
        id: 'rev-008',
        author: 'Pooja Tandon',
        city: 'Kolkata',
        rating: 5,
        date: 'Sep 25, 2026',
        comment: 'So soft and practical. It has become my go-to travel wrap for flights.',
        verifiedPurchase: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 3. MEN'S CLOTHING
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'clt-men-phr-001',
    sku: 'NT-FW26-MPHR-01',
    name: 'Classic Tweed Wool Men\'s Pheran with Pocket Lining',
    slug: 'classic-tweed-wool-mens-pheran',
    gender: 'men',
    primaryCategory: 'men',
    categoryLabel: 'Men',
    subCategory: 'Pherans',
    shortDesc: 'Heavyweight handwoven tweed wool with traditional side kangaroo pockets and subtle tonal cord piping along the neck placket.',
    longDesc: `The definitive Kashmiri garment for men, refined for modern winter lifestyles. Built with robust heavy-gauge woolen tweed, it provides complete wind chill defense during harsh sub-zero temperatures.\n\nDesigned with traditional inner hand-warmer openings (kangri slits) reinforced with twill cotton lining, a comfortable roominess to wear over knits or kurtas, and structured shoulders that maintain a commanding silhouette.`,
    editorialStory: 'Woven from hardy local wool on shuttle pit-looms in the foothills of Gulmarg.',
    price: 11500,
    mrp: 15500,
    image: '/images/campaign-mens-style-story.jpg',
    secondaryImage: '/images/crafts-pherans.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-jackets.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    lifestyleImage: '/images/campaign-mens-style-story.jpg',
    processImage: '/images/crafts-artisan-hands.jpg',
    additionalImages: [
      '/images/campaign-mens-style-story.jpg',
      '/images/crafts-pherans.jpg',
      '/images/crafts-jackets.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['38 (Chest 44)', '40 (Chest 46)', '42 (Chest 48)', '44 (Chest 50)', '46 (Chest 52)'],
    colorOptions: [
      { name: 'Herringbone Charcoal', hex: '#2E3236' },
      { name: 'Highland Olive', hex: '#3B4A37' },
      { name: 'Earthy Walnut Brown', hex: '#4B382A' },
      { name: 'Navy Tweed', hex: '#1C283F' },
    ],
    material: '100% Heavy Pure Wool Tweed (Windproof, naturally water-resistant)',
    craft: 'Handloom Tweed Weave with Tailored Twill Lining',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Everyday',
    fit: 'Traditional Men\'s Relaxed Roomy Cut',
    dimensions: 'Length: 46", Chest: 48", Shoulder: 19", Sleeve: 25"',
    provenance: {
      origin: 'Tangmarg / Gulmarg Foothills, Kashmir',
      artisanGroup: 'Gulmarg Woolen Crafts Guild',
      craftTradition: 'Traditional Tweed Handloom',
      material: '100% Himalayan Sheep Wool with Cotton Flannel Lining',
      technique: 'Heavy twill handloom weaving',
      artisanHours: 36,
      giTagCertified: false,
      care: 'Dry clean recommended. Air out in fresh shaded breeze between wears.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 11,
    tags: ['pheran', 'men', 'wool', 'tweed', 'herringbone', 'gulmarg', 'fw26'],
    reviews: [
      {
        id: 'rev-009',
        author: 'Karan Singhal',
        city: 'Dehradun',
        rating: 5,
        date: 'Oct 3, 2026',
        comment: 'Outstanding quality. Thick, windproof and gives that authentic mountain look without feeling heavy.',
        verifiedPurchase: true,
      },
    ],
    pairWithSlug: 'mens-heritage-pashmina-muffler',
  },
  {
    id: 'clt-men-jkt-001',
    sku: 'NT-FW26-MJKT-01',
    name: 'Artisanal Kani Wool Tweed Overcoat',
    slug: 'artisanal-kani-wool-tweed-overcoat',
    gender: 'men',
    primaryCategory: 'jackets-coats',
    categoryLabel: 'Jackets & Coats',
    subCategory: 'Long Coats',
    shortDesc: 'Double-breasted long winter coat combining structured English charcoal wool with Kani-woven cuffs and inner lapel facing.',
    longDesc: `Where Savile Row tailoring meets centuries-old Himalayan craftsmanship. Tailored from 600 GSM pure melton wool, this structured overcoat incorporates authentic Kani-woven textile panels inside the lapels, collar underband, and pocket trims.\n\nFeatures genuine horn buttons, satin Bemberg lining, internal ticket pockets, and a back vent for ease of movement. Uncompromising luxury for cold-climate business travel, formal events, and winter city living.`,
    editorialStory: 'Designed in collaboration with Kashmiri master tailors and Kanihama loom masters.',
    price: 28900,
    mrp: 38000,
    image: '/images/crafts-jackets.jpg',
    secondaryImage: '/images/campaign-mens-style-story.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-jackets.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    lifestyleImage: '/images/campaign-mens-style-story.jpg',
    processImage: '/images/crafts-artisan-hands.jpg',
    additionalImages: [
      '/images/crafts-jackets.jpg',
      '/images/campaign-mens-style-story.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['38 (S)', '40 (M)', '42 (L)', '44 (XL)', '46 (XXL)'],
    colorOptions: [
      { name: 'Charcoal with Kani Accents', hex: '#2B2E33' },
      { name: 'Midnight Navy with Kani Accents', hex: '#16223B' },
      { name: 'Camel Tan with Kani Accents', hex: '#B89264' },
    ],
    material: '100% Virgin Melton Wool (600 GSM) with Pure Kani Silk-Wool Insets',
    craft: 'Structured Bespoke Tailoring with Kani Loom Insets',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Luxury',
    fit: 'Tailored Structured Overcoat Cut',
    dimensions: 'Length: 42", Chest: 44", Shoulder: 18.5", Sleeve: 25.5"',
    provenance: {
      origin: 'Srinagar Craft Hub & Noida Atelier',
      artisanGroup: 'Master Tailor Ghulam Nabi & Kanihama Guild',
      craftTradition: 'Heritage Textile Inset Tailoring',
      material: 'Virgin Wool, Bemberg Satin Lining, Handwoven Kani Textile',
      technique: 'Canvas chest piece construction with hand-sewn buttonholes',
      artisanHours: 68,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-KANI-2026-0891-INS',
      care: 'Professional dry clean only. Hang on wide contoured wooden hanger.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 5,
    tags: ['coat', 'men', 'overcoat', 'kani', 'wool', 'tailored', 'luxury', 'fw26'],
    reviews: [
      {
        id: 'rev-010',
        author: 'Vikramaditya Rao',
        city: 'New Delhi',
        rating: 5,
        date: 'Oct 5, 2026',
        comment: 'Worth every rupee. The Kani reveal inside the collar is pure bespoke poetry. Exceptional drape.',
        verifiedPurchase: true,
      },
    ],
    pairWithSlug: 'mens-heritage-pashmina-muffler',
  },
  {
    id: 'clt-men-jkt-002',
    sku: 'NT-FW26-MJKT-02',
    name: 'Downtown Srinagar Hand-Embroidered Nehru Jacket',
    slug: 'downtown-srinagar-hand-embroidered-nehru-jacket',
    gender: 'men',
    primaryCategory: 'jackets-coats',
    categoryLabel: 'Jackets & Coats',
    subCategory: 'Nehru Jackets',
    shortDesc: 'Fine wool sleeveless Nehru jacket / bandi featuring subtle tone-on-tone Sozni floral vine work along the mandarin collar and chest welt pocket.',
    longDesc: `An essential festive layer for Indian men. Crafted in midnight navy and forest green wool, this Nehru jacket pairs seamlessly over silk kurtas, linen shirts, or western formal trousers.\n\nHand-embroidered with understated Sozni needlework that reveals itself only upon closer inspection, offering timeless sophistication for Diwali celebrations, wedding cocktail nights, and family gatherings.`,
    price: 8500,
    mrp: 11000,
    image: '/images/crafts-jackets.jpg',
    secondaryImage: '/images/crafts-artisan-hands.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-jackets.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-jackets.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['38 (S)', '40 (M)', '42 (L)', '44 (XL)', '46 (XXL)'],
    colorOptions: [
      { name: 'Midnight Navy', hex: '#16223B' },
      { name: 'Forest Green', hex: '#1A3F2C' },
      { name: 'Burgundy Maroon', hex: '#5E1B26' },
      { name: 'Raw Silk Beige', hex: '#D8CDBA' },
    ],
    material: '100% Pure Fine Wool (Medium weight, structured canvas)',
    craft: 'Tonal Sozni Hand Needlework',
    warmthRating: 'Medium (4°C - 12°C)',
    length: 'Short',
    occasion: 'Festive',
    fit: 'Tailored Sleeveless Bandi Fit',
    dimensions: 'Length: 28", Chest: 42", Shoulder: 16"',
    provenance: {
      origin: 'Fateh Kadal, Downtown Srinagar',
      artisanGroup: 'Downtown Master Embroiderers Guild',
      craftTradition: 'Tone-on-tone Sozni needlecraft',
      material: 'Kashmiri Wool with Silk Thread Accents',
      technique: 'Pointed needle anchor work',
      artisanHours: 26,
      giTagCertified: false,
      care: 'Dry clean only.',
    },
    isNew: false,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 14,
    tags: ['jacket', 'men', 'nehru', 'bandi', 'sozni', 'festive', 'wedding', 'fw26'],
    reviews: [
      {
        id: 'rev-011',
        author: 'Sameer Chawla',
        city: 'Jaipur',
        rating: 5,
        date: 'Sep 30, 2026',
        comment: 'The collar needlework is immaculate. It elevated my plain kurta set into something truly distinguished.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-men-krt-001',
    sku: 'NT-FW26-MKRT-01',
    name: 'Kashmiri Wool Winter Kurta & Trousers Set',
    slug: 'kashmiri-wool-winter-kurta-trousers-set',
    gender: 'men',
    primaryCategory: 'men',
    categoryLabel: 'Men',
    subCategory: 'Sets',
    shortDesc: 'Refined winter kurta tailored from soft spun merino-blend wool, accompanied by coordinating straight trousers. Minimalist piping on collar.',
    longDesc: `Elevated warmth for festive winter occasions. The kurta features a comfortable relaxed cut with side seam pockets, mandarin collar, and concealed mother-of-pearl button placket.\n\nPaired with matching structured trousers with drawstring-elastic waist. Sized generously to allow seamless layering under overcoats or Nehru jackets.`,
    price: 8900,
    mrp: 11900,
    image: '/images/crafts-pherans.jpg',
    secondaryImage: '/images/crafts-winterwear.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-pherans.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-pherans.jpg',
      '/images/crafts-winterwear.jpg',
    ],
    sizes: ['38 (S)', '40 (M)', '42 (L)', '44 (XL)', '46 (XXL)'],
    colorOptions: [
      { name: 'Warm Sand', hex: '#C7B299' },
      { name: 'Charcoal Grey', hex: '#3E4247' },
      { name: 'Deep Indigo', hex: '#1B2A4A' },
    ],
    material: 'Merino Wool & Cotton Blend (Breathable winter weave)',
    craft: 'Artisanal Tailoring with Fine Piping',
    warmthRating: 'Medium (4°C - 12°C)',
    length: 'Long',
    occasion: 'Festive',
    fit: 'Comfort Regular Kurta Fit',
    dimensions: 'Kurta Length: 42", Chest: 44", Bottom Length: 40"',
    provenance: {
      origin: 'Srinagar / Noida Atelier',
      artisanGroup: 'Nutty Tales Tailoring Collective',
      craftTradition: 'Traditional Indian Winter Kurta',
      material: 'Blended Wool & Cotton',
      technique: 'Single-needle tailoring with bound seams',
      artisanHours: 18,
      giTagCertified: false,
      care: 'Dry clean recommended.',
    },
    isNew: true,
    isBestseller: false,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 16,
    tags: ['kurta', 'men', 'set', 'wool', 'co-ord', 'festive', 'winter'],
    reviews: [
      {
        id: 'rev-012',
        author: 'Rohan Mehra',
        city: 'Lucknow',
        rating: 5,
        date: 'Sep 19, 2026',
        comment: 'So hard to find proper winter kurtas that don’t look bulky. This fits beautifully.',
        verifiedPurchase: true,
      },
    ],
    pairWithSlug: 'downtown-srinagar-hand-embroidered-nehru-jacket',
  },
  {
    id: 'clt-men-acc-001',
    sku: 'NT-FW26-MACC-01',
    name: 'Men\'s Heritage Pashmina Muffler (Reversible Weave)',
    slug: 'mens-heritage-pashmina-muffler',
    gender: 'men',
    primaryCategory: 'accessories',
    categoryLabel: 'Accessories',
    subCategory: 'Mufflers',
    shortDesc: 'Pure Himalayan Pashmina muffler woven in a double-faced two-tone twill weave (Charcoal / Camel). Featherlight warmth for suit coats.',
    longDesc: `The quintessential cold-weather essential for the discerning gentleman. Measuring 180 cm × 35 cm, it tucks smoothly inside suit overcoats, blazers, or pherans without adding excessive volume.\n\nWoven from pure Changthangi cashmere with soft eyelashes fringes. Reversible dual-tone weaving allows switching between deep charcoal and warm camel with a single twist.`,
    price: 9800,
    mrp: 13500,
    image: '/images/crafts-accessories.jpg',
    secondaryImage: '/images/crafts-stoles.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-accessories.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-accessories.jpg',
      '/images/crafts-stoles.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['One Size (180 cm × 35 cm)'],
    colorOptions: [
      { name: 'Charcoal & Camel (Reversible)', hex: '#373A3C' },
      { name: 'Navy & Slate (Reversible)', hex: '#16223B' },
      { name: 'Burgundy & Black (Reversible)', hex: '#582138' },
    ],
    material: '100% Certified Himalayan Pashmina',
    craft: 'Double-Faced Twill Handloom Weave',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Short',
    occasion: 'Luxury',
    fit: 'Neck Wrap',
    dimensions: '180 cm × 35 cm (70" × 14")',
    provenance: {
      origin: 'Downtown Srinagar, Kashmir',
      artisanGroup: 'Bagh-e-Ali Cashmere Weavers',
      craftTradition: 'Traditional Handloom Twill Weave',
      material: '100% Changthangi Mountain Pashmina (14.5 Microns)',
      technique: 'Four-pedal shuttle loom reversible weave',
      artisanHours: 32,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-PASH-2026-0814',
      care: 'Strictly dry clean only.',
    },
    isNew: false,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: false,
    stockStatus: 'IN_STOCK',
    stockCount: 19,
    tags: ['muffler', 'men', 'pashmina', 'reversible', 'accessories', 'luxury', 'travel'],
    reviews: [
      {
        id: 'rev-013',
        author: 'Nikhil Agarwal',
        city: 'Mumbai',
        rating: 5,
        date: 'Oct 2, 2026',
        comment: 'Extremely soft against the neck, completely non-itchy. The reversible colorway makes it versatile.',
        verifiedPurchase: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 4. WOMEN'S JACKETS, CAPES & WINTER WEAR
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'clt-wom-cpe-001',
    sku: 'NT-FW26-WCPE-01',
    name: 'Pampore Saffron Dye Wool Cape with Aari Embroidery',
    slug: 'pampore-saffron-dye-wool-cape',
    gender: 'women',
    primaryCategory: 'winter-wear',
    categoryLabel: 'Winter Wear',
    subCategory: 'Capes & Ponchos',
    shortDesc: 'Dramatic circular wool cape dyed in golden saffron hue, framed by cascading Aari autumn foliage and concealed front hook closure.',
    longDesc: `A breathtaking statement silhouette for winter galas, destination weddings, and cultural evenings. Cut in a generous 360-degree circular drape that cascades naturally over the shoulders.\n\nHand-embroidered along the sweeping hemline with traditional chinar leaves and blooming iris motifs. Lined with smooth silk crepe so it slides easily over sleeves without bunching.`,
    price: 15800,
    mrp: 21000,
    image: '/images/crafts-winterwear.jpg',
    secondaryImage: '/images/campaign-wear-the-story.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-winterwear.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    lifestyleImage: '/images/campaign-wear-the-story.jpg',
    additionalImages: [
      '/images/crafts-winterwear.jpg',
      '/images/campaign-wear-the-story.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['Free Size (Generous Draping Sweep)'],
    colorOptions: [
      { name: 'Pampore Saffron Gold', hex: '#D49B35' },
      { name: 'Forest Emerald', hex: '#165B4C' },
      { name: 'Vintage Black', hex: '#1C1C1C' },
    ],
    material: '100% Pure Wool with Silk Crepe Lining',
    craft: 'Sweeping Hemline Aari Embroidery',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Wedding',
    fit: '360° Circular Draped Cape',
    dimensions: 'Sweep Radius: 38", Neck Circumference: 18"',
    provenance: {
      origin: 'Pampore & Downtown Srinagar',
      artisanGroup: 'Saffron Valley Artisan Guild',
      craftTradition: 'Traditional Aari Hookwork',
      material: 'Kashmir Wool with Silk Crepe and Organic Saffron Pigments',
      technique: 'Continuous hook stitch along curved perimeter',
      artisanHours: 58,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-AARI-2026-0391',
      care: 'Dry clean only. Store on padded coat hanger.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 6,
    tags: ['cape', 'women', 'wool', 'aari', 'saffron', 'wedding', 'winter-wear', 'fw26'],
    reviews: [
      {
        id: 'rev-014',
        author: 'Sunita Singhania',
        city: 'Kolkata',
        rating: 5,
        date: 'Oct 4, 2026',
        comment: 'This cape is a showstopper. The golden saffron hue is glowing in person and the drape is pure royalty.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-wom-jkt-001',
    sku: 'NT-FW26-WJKT-01',
    name: 'Kashmiri Embroidered Velvet Crop Jacket',
    slug: 'kashmiri-embroidered-velvet-crop-jacket',
    gender: 'women',
    primaryCategory: 'jackets-coats',
    categoryLabel: 'Jackets & Coats',
    subCategory: 'Short Jackets',
    shortDesc: 'Tailored black velvet short jacket with intricate metallic gold Tilla and silk Aari work across the mandarin collar and front panels.',
    longDesc: `The ultimate luxury fusion piece. Cut to sit cleanly at the high hip, it pairs effortlessly over sarees, lehengas, high-waisted trousers, or evening slips.\n\nCrafted from premium deep-pile velvet with structured shoulders and an open front secured by discreet hook-and-eye clasps.`,
    price: 13500,
    mrp: 17500,
    image: '/images/crafts-jackets.jpg',
    secondaryImage: '/images/crafts-artisan-hands.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-jackets.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-jackets.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['XS (36)', 'S (38)', 'M (40)', 'L (42)', 'XL (44)'],
    colorOptions: [
      { name: 'Onyx Black & Gold', hex: '#1C1C1C' },
      { name: 'Deep Burgundy & Gold', hex: '#631B26' },
      { name: 'Royal Emerald & Gold', hex: '#165B4C' },
    ],
    material: 'Plush Silk Velvet with Satin Lining',
    craft: 'Tilla Metallic & Silk Aari Embroidery',
    warmthRating: 'Medium (4°C - 12°C)',
    length: 'Short',
    occasion: 'Festive',
    fit: 'Tailored Structured Crop',
    dimensions: 'Length: 20", Chest: 38", Shoulder: 15.5", Sleeve: 23"',
    provenance: {
      origin: 'Zadibal, Srinagar, Kashmir',
      artisanGroup: 'Mir Tilla Guild',
      craftTradition: 'Tilla Needlework on Velvet',
      material: 'Plush Velvet, Gilded Metallic Thread, Satin Lining',
      technique: 'Pointed needle anchor stitch',
      artisanHours: 48,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-TILLA-2026-0520',
      care: 'Dry clean only.',
    },
    isNew: false,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 9,
    tags: ['jacket', 'women', 'velvet', 'tilla', 'crop', 'festive', 'wedding'],
    reviews: [
      {
        id: 'rev-015',
        author: 'Ananya Deshmukh',
        city: 'Pune',
        rating: 5,
        date: 'Sep 27, 2026',
        comment: 'Wore this over a plain black silk saree and looked like royalty. Great tailored fit.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-wom-wnt-001',
    sku: 'NT-FW26-WWNT-01',
    name: 'Fine Cashmere-Blend Winter Cardigan & Co-ord Set',
    slug: 'fine-cashmere-blend-winter-cardigan-set',
    gender: 'women',
    primaryCategory: 'winter-wear',
    categoryLabel: 'Winter Wear',
    subCategory: 'Co-ords',
    shortDesc: 'Ribbed knit cashmere-wool co-ord featuring a longline relaxed cardigan and matching straight palazzo pants. Tonal horn buttons.',
    longDesc: `The epitome of effortless winter luxury. Made from 30% Himalayan Cashmere and 70% Extra-fine Merino wool, spun into an ultra-soft 12-gauge rib knit.\n\nBreathable, deeply warm, and designed for travel lounging, resort stays, and fireside relaxation.`,
    price: 11900,
    mrp: 15900,
    image: '/images/crafts-winterwear.jpg',
    secondaryImage: '/images/crafts-stoles.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-winterwear.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-winterwear.jpg',
      '/images/crafts-stoles.jpg',
    ],
    sizes: ['S (38)', 'M (40)', 'L (42)', 'XL (44)'],
    colorOptions: [
      { name: 'Warm Camel', hex: '#C19A6B' },
      { name: 'Soft Cream', hex: '#F7F3E7' },
      { name: 'Charcoal Melange', hex: '#3E4247' },
    ],
    material: '30% Himalayan Cashmere, 70% Extra-Fine Merino Wool',
    craft: '12-Gauge Seamless Rib Knit',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Everyday',
    fit: 'Relaxed Ribbed Knit Silhouette',
    dimensions: 'Cardigan Length: 36", Pant Inseam: 30"',
    provenance: {
      origin: 'Kashmir Valley & Ludhiana Knit Lab',
      artisanGroup: 'Nutty Tales Knitwear Collaborative',
      craftTradition: 'Fine Himalayan Wool Spun Knitting',
      material: 'Cashmere & Extra-Fine Merino Blend',
      technique: 'Seamless circular rib knitting',
      artisanHours: 22,
      giTagCertified: false,
      care: 'Gentle hand wash cold with wool wash or dry clean. Dry flat.',
    },
    isNew: true,
    isBestseller: false,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 12,
    tags: ['knitwear', 'co-ord', 'women', 'cashmere', 'merino', 'cardigan', 'lounge', 'travel'],
    reviews: [
      {
        id: 'rev-016',
        author: 'Tanya Bhardwaj',
        city: 'Gurugram',
        rating: 5,
        date: 'Oct 1, 2026',
        comment: 'Insanely soft. Doesn’t pill at all. Feels like a hug in the cold.',
        verifiedPurchase: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 5. KIDS & FAMILY COLLECTIONS
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'clt-kds-phr-001',
    sku: 'NT-FW26-KPHR-01',
    name: 'Little Chinar Pure Wool Boys Pheran & Beanie Set',
    slug: 'little-chinar-wool-boys-pheran-set',
    gender: 'kids',
    primaryCategory: 'kids',
    categoryLabel: 'Kids',
    subCategory: 'Boys',
    shortDesc: 'Pure Kashmir wool traditional boys pheran with soft cotton lining, side pockets, and a matching hand-knitted pom-pom woolen beanie.',
    longDesc: `Heritage warmth for little explorers. Lined completely with 100% breathable organic cotton so there is zero itching against delicate skin.\n\nFeatures charming chinar leaf embroidery on the neckline, easy snap buttons for fuss-free dressing, and roomy proportions that allow easy movement and snowball play.`,
    price: 4800,
    mrp: 6500,
    image: '/images/crafts-pherans.jpg',
    secondaryImage: '/images/crafts-accessories.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-pherans.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-pherans.jpg',
      '/images/crafts-accessories.jpg',
    ],
    sizes: ['2-3 Yrs', '4-5 Yrs', '6-7 Yrs', '8-9 Yrs', '10-12 Yrs'],
    colorOptions: [
      { name: 'Highland Olive', hex: '#3B4A37' },
      { name: 'Navy Tweed', hex: '#1C283F' },
      { name: 'Oatmeal Beige', hex: '#D2C4A7' },
    ],
    material: 'Pure Wool with 100% Organic Cotton Anti-Itch Lining',
    craft: 'Delicate Chinar Aari Needlework',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Mid',
    occasion: 'Festive',
    fit: 'Easy Relaxed Kids Pheran',
    dimensions: 'Age-graded standard dimensions',
    provenance: {
      origin: 'Budgam Valley, Kashmir',
      artisanGroup: 'Budgam Valley Craft Collective',
      craftTradition: 'Traditional Children\'s Woolcraft',
      material: 'Local Sheep Wool & Organic Cotton Lining',
      technique: 'Soft chain-stitch needlework',
      artisanHours: 16,
      giTagCertified: false,
      care: 'Dry clean or gentle cold hand wash.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 14,
    tags: ['kids', 'boys', 'pheran', 'wool', 'chinar', 'beanie', 'family'],
    reviews: [
      {
        id: 'rev-017',
        author: 'Deepika Malhotra',
        city: 'Srinagar / Delhi',
        rating: 5,
        date: 'Oct 3, 2026',
        comment: 'My 5-year-old wore this in Gulmarg and stayed warm all day. The cotton lining is a lifesaver.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-kds-phr-002',
    sku: 'NT-FW26-KPHR-02',
    name: 'Girls Kashmiri Velvet & Tilla Festive Pheran',
    slug: 'girls-kashmiri-velvet-tilla-festive-pheran',
    gender: 'kids',
    primaryCategory: 'kids',
    categoryLabel: 'Kids',
    subCategory: 'Girls',
    shortDesc: 'Soft micro-velvet pheran in ruby wine and emerald, detailed with gentle gold thread Tilla work along the yoke. Lined in soft cotton voile.',
    longDesc: `A miniature masterpiece for festive celebrations, weddings, and family portraits. Sized for young girls with gentle non-scratch Tilla accents that catch the light beautifully.\n\nRoomy enough to wear comfortably over thermal innerwear during outdoor winter festivals.`,
    price: 5400,
    mrp: 7200,
    image: '/images/crafts-pherans.jpg',
    secondaryImage: '/images/crafts-artisan-hands.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-pherans.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-pherans.jpg',
      '/images/crafts-artisan-hands.jpg',
    ],
    sizes: ['2-3 Yrs', '4-5 Yrs', '6-7 Yrs', '8-9 Yrs', '10-12 Yrs'],
    colorOptions: [
      { name: 'Ruby Wine', hex: '#6B1F2D' },
      { name: 'Emerald Green', hex: '#165B4C' },
      { name: 'Midnight Navy', hex: '#16223B' },
    ],
    material: 'Soft Silk Micro-Velvet with Cotton Voile Lining',
    craft: 'Gentle Tilla Metallic Needlework',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Wedding',
    fit: 'Comfort Flowing Girls Silhouette',
    dimensions: 'Age-graded standard dimensions',
    provenance: {
      origin: 'Zadibal, Downtown Srinagar',
      artisanGroup: 'Mir Tilla Guild',
      craftTradition: 'Traditional Festive Needlework',
      material: 'Plush Velvet, Cotton Voile, Tilla Thread',
      technique: 'Hand needlework',
      artisanHours: 20,
      giTagCertified: false,
      care: 'Dry clean only.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 10,
    tags: ['kids', 'girls', 'pheran', 'velvet', 'tilla', 'wedding', 'festive'],
    reviews: [
      {
        id: 'rev-018',
        author: 'Zainab Qureshi',
        city: 'Hyderabad',
        rating: 5,
        date: 'Sep 24, 2026',
        comment: 'So adorable on my daughter! High quality velvet and the gold work is very neat.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-fam-set-001',
    sku: 'NT-FW26-FAM-01',
    name: 'Mother & Daughter Coordinated Kashmir Pheran Set',
    slug: 'mother-daughter-coordinated-kashmir-pheran-set',
    gender: 'women',
    primaryCategory: 'kids',
    categoryLabel: 'Kids',
    subCategory: 'Family Collections',
    shortDesc: 'A coordinated heirloom pairing: One Adult Imperial Velvet/Wool Pheran and One Matching Girls Festive Pheran with harmonious floral embroidery.',
    longDesc: `Celebrate family heritage and memorable winter holidays together. This pair features matching colorways and complementary Aari/Tilla embroidery motifs designed in harmony.\n\nDelivered in an executive dual-compartment presentation box with personalized artisan gift notes.`,
    price: 22500,
    mrp: 29500,
    image: '/images/campaign-wear-the-story.jpg',
    secondaryImage: '/images/crafts-pherans.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-pherans.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    lifestyleImage: '/images/campaign-wear-the-story.jpg',
    additionalImages: [
      '/images/campaign-wear-the-story.jpg',
      '/images/crafts-pherans.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['Adult M + Child 4-5 Yrs', 'Adult L + Child 6-7 Yrs', 'Adult M + Child 8-9 Yrs', 'Custom Sizing'],
    colorOptions: [
      { name: 'Imperial Burgundy', hex: '#631B26' },
      { name: 'Royal Emerald', hex: '#165B4C' },
      { name: 'Midnight Navy', hex: '#16223B' },
    ],
    material: 'Plush Velvet / Pure Wool with Soft Breathable Linings',
    craft: 'Coordinated Tilla & Aari Hand Needlework',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Long',
    occasion: 'Wedding',
    fit: 'Coordinated Relaxed Silhouettes',
    dimensions: 'Both garments customized to respective sizes',
    provenance: {
      origin: 'Zadibal & Charar-i-Sharief, Kashmir',
      artisanGroup: 'Nutty Tales Heritage Family Atelier',
      craftTradition: 'Heirloom Coordinated Needlework',
      material: 'Plush Velvet, Wool, Metallic Thread',
      technique: 'Matched hand embroidery',
      artisanHours: 95,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-FAM-2026-0041',
      care: 'Dry clean only.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: true,
    stockStatus: 'IN_STOCK',
    stockCount: 5,
    tags: ['family', 'mother-daughter', 'pheran', 'set', 'kids', 'women', 'heirloom'],
    reviews: [
      {
        id: 'rev-019',
        author: 'Simran Jolly',
        city: 'Amritsar',
        rating: 5,
        date: 'Oct 5, 2026',
        comment: 'The sweetest Diwali gift to myself and my daughter. The photos we took turned out unforgettable.',
        verifiedPurchase: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────────
  // 6. ACCESSORIES & HERITAGE HOME
  // ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'clt-acc-001',
    sku: 'NT-FW26-ACC-01',
    name: 'Kashmiri Hand-Embroidered Pure Wool Gloves & Beanie Set',
    slug: 'kashmiri-wool-gloves-beanie-set',
    gender: 'unisex',
    primaryCategory: 'accessories',
    categoryLabel: 'Accessories',
    subCategory: 'Gloves',
    shortDesc: 'Soft merino-wool touch-screen compatible gloves paired with a fold-over ribbed beanie, both accented with delicate Aari Chinar embroidery.',
    longDesc: `Stay connected in sub-zero climates without exposing your skin to icy winds. Knitted from ultra-fine Merino wool with conductive touch-screen thread woven into the thumb and forefinger.\n\nAccented with miniature hand-embroidered Chinar leaves on the cuff and beanie brim.`,
    price: 2800,
    mrp: 3800,
    image: '/images/crafts-accessories.jpg',
    secondaryImage: '/images/crafts-winterwear.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-accessories.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-accessories.jpg',
      '/images/crafts-winterwear.jpg',
    ],
    sizes: ['Free Size (Elasticated Knit)'],
    colorOptions: [
      { name: 'Oatmeal Beige', hex: '#D2C4A7' },
      { name: 'Charcoal Grey', hex: '#373A3C' },
      { name: 'Deep Burgundy', hex: '#582138' },
    ],
    material: '100% Merino Wool with Conductive Touch-Screen Yarn',
    craft: 'Miniature Chinar Aari Needlework',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Short',
    occasion: 'Everyday',
    fit: 'Form-Fitting Stretch Knit',
    dimensions: 'Standard glove & beanie stretch fit',
    provenance: {
      origin: 'Baramulla / Srinagar, Kashmir',
      artisanGroup: 'Valley Knitwear Guild',
      craftTradition: 'Fine Needlepoint on Knits',
      material: 'Merino Wool',
      technique: 'Micro-hook chain-stitch',
      artisanHours: 14,
      giTagCertified: false,
      care: 'Gentle hand wash cold.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: false,
    tryWithSiSupported: false,
    stockStatus: 'IN_STOCK',
    stockCount: 30,
    tags: ['gloves', 'beanie', 'accessories', 'merino', 'touch-screen', 'travel', 'unisex'],
    reviews: [
      {
        id: 'rev-020',
        author: 'Varun Nair',
        city: 'Bengaluru',
        rating: 5,
        date: 'Oct 3, 2026',
        comment: 'Worked brilliantly in Shimla! The touch screen fingertips actually work with iPhone screens.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-hom-001',
    sku: 'NT-FW26-HOM-01',
    name: 'Carved Kashmiri Walnut Wood Keepsake & Jewelry Chest',
    slug: 'carved-kashmiri-walnut-wood-keepsake-chest',
    gender: 'unisex',
    primaryCategory: 'heritage-home',
    categoryLabel: 'Heritage Home',
    subCategory: 'Walnut Wood',
    shortDesc: 'Deep-relief hand-carved solid walnut root wood chest featuring the legendary Dragon & Grapevine motif. Velvet-lined interior with secret brass slide lock.',
    longDesc: `Kashmiri walnut wood carving (Dun Kul) is one of the world's most intricate sculptural crafts. Sourced from seasoned root wood of fallen Juglans regia trees, which exhibits dark rippled grain and superior density.\n\nHand-carved with steel chisels without templates, requiring weeks of patient carving, and finished with natural beeswax buffing. Velvet lined with a two-tier lift-out tray.`,
    price: 8500,
    mrp: 12000,
    image: '/images/dark-wood-gourmet-tray.jpg',
    secondaryImage: '/images/crafts-artisan-hands.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/dark-wood-gourmet-tray.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/dark-wood-gourmet-tray.jpg',
      '/images/crafts-artisan-hands.jpg',
      '/images/crafts-gifting-box.jpg',
    ],
    sizes: ['10" × 6" × 4" (Chest)'],
    colorOptions: [
      { name: 'Natural Waxed Walnut', hex: '#4A3525' },
    ],
    material: '100% Seasoned Kashmiri Walnut Root Wood (Dun Kul)',
    craft: 'Walnut Wood Carving (Deep Relief / Undercut)',
    warmthRating: 'Light (12°C - 20°C)',
    length: 'Short',
    occasion: 'Luxury',
    fit: 'Desk / Vanity Keepsake',
    dimensions: '10" × 6" × 4" (Weight: 1.4 kg)',
    provenance: {
      origin: 'Fateh Kadal, Downtown Srinagar, Kashmir',
      artisanGroup: 'Master Craftsman Nazir Ahmad Woodcarvers',
      craftTradition: 'Walnut Wood Carving (Deep Relief / Undercut)',
      material: '100% Seasoned Kashmiri Walnut Root Wood',
      technique: 'Hand-carved with steel chisels and polished with pure walnut oil',
      artisanHours: 54,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-WOOD-2026-0623',
      care: 'Wipe with dry microfiber cloth. Polish once a year with pure walnut oil.',
    },
    isNew: false,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: false,
    stockStatus: 'IN_STOCK',
    stockCount: 8,
    tags: ['walnut-wood', 'wood-carving', 'home-heritage', 'box', 'gi-certified', 'keepsake'],
    reviews: [
      {
        id: 'rev-021',
        author: 'Dr. Radhika Sen',
        city: 'Kolkata',
        rating: 5,
        date: 'Sep 22, 2026',
        comment: 'The depth of the carving is incredible. The wood aroma fills the dressing room every time I open it.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-hom-002',
    sku: 'NT-FW26-HOM-02',
    name: 'Hand-Painted Kashmiri Papier-Mâché Keepsake Box',
    slug: 'hand-painted-kashmiri-papier-mache-keepsake-box',
    gender: 'unisex',
    primaryCategory: 'heritage-home',
    categoryLabel: 'Heritage Home',
    subCategory: 'Papier-Mâché',
    shortDesc: 'Artisanal lacquered box crafted from recycled paper pulp, hand-painted with genuine 24k gold leaf accents in the legendary Hazara Gulzar (Thousand Flowers) pattern.',
    longDesc: `Papier-mâché was introduced to Kashmir in the 14th century by Sufi saint Mir Sayyid Ali Hamadani from Persia. The craft involves two stages: Sakhtsazi (shaping the mashed paper pulp in wooden moulds) and Naqqashi (intricate painting by master artists).\n\nDecorated with the 'Hazara Gulzar' motif featuring miniature roses, nightingales, and gold dust, then coated with multiple layers of crystal-clear amber lacquer for waterproof durability.`,
    price: 3200,
    mrp: 4500,
    image: '/images/crafts-gifting-box.jpg',
    secondaryImage: '/images/crafts-artisan-hands.jpg',
    detailImage: '/images/crafts-artisan-hands.jpg',
    textureImage: '/images/crafts-gifting-box.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-gifting-box.jpg',
      '/images/crafts-artisan-hands.jpg',
    ],
    sizes: ['6" × 4" × 2.5"'],
    colorOptions: [
      { name: 'Royal Emerald & Gold', hex: '#165B4C' },
      { name: 'Midnight Navy & Gold', hex: '#16223B' },
      { name: 'Ivory Floral Gold', hex: '#F7F3E9' },
    ],
    material: 'Recycled paper pulp, amber lacquer, mineral pigments & 24k gold leaf',
    craft: 'Sakhtsazi & Naqqashi Miniature Painting',
    warmthRating: 'Light (12°C - 20°C)',
    length: 'Short',
    occasion: 'Everyday',
    fit: 'Keepsake Box',
    dimensions: '6" × 4" × 2.5"',
    provenance: {
      origin: 'Zadibal, Srinagar, Kashmir',
      artisanGroup: 'Mir Papier-Mâché Guild',
      craftTradition: 'Sakhtsazi & Naqqashi Miniature Painting',
      material: 'Paper pulp, mineral pigments, natural lacquer',
      technique: 'Multi-layer stone rubbing and fine hairbrush painting',
      artisanHours: 38,
      giTagCertified: true,
      giCertificateNo: 'JK-GI-PAPIER-2026-0177',
      care: 'Wipe with soft dry cloth. Avoid soaking in water.',
    },
    isNew: false,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: false,
    stockStatus: 'IN_STOCK',
    stockCount: 15,
    tags: ['papier-mache', 'hand-painted', 'home-heritage', 'gold-leaf', 'box', 'gift'],
    reviews: [
      {
        id: 'rev-022',
        author: 'Malini Bose',
        city: 'Chennai',
        rating: 5,
        date: 'Sep 18, 2026',
        comment: 'The fine brushstrokes and gold leaf work are exquisite. Packaged very securely.',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'clt-hom-003',
    sku: 'NT-FW26-HOM-03',
    name: 'Kashmir Heritage Luxury Hamper (Winter 2026 Edition)',
    slug: 'kashmiri-heritage-luxury-hamper',
    gender: 'unisex',
    primaryCategory: 'heritage-home',
    categoryLabel: 'Heritage Home',
    subCategory: 'Heritage Gifting',
    shortDesc: 'The ultimate royal gift: Handcrafted Papier-Mâché keepsake box, 1g Pure Kashmiri Mongra Saffron, 500g Acacia Honey, 250g Kagzi Walnuts, and a Pure Cashmere Stole.',
    longDesc: `Where Nutty Tales Foods and Crafts & Heritage merge into an unforgettable experience. Presented in an exquisite emerald-and-gold keepsake box featuring:\n\n• 1 × Fine Kashmiri Cashmere Stole (Unisex Ivory / Slate)\n• 1 × 1g Pure Kashmiri Mongra Saffron Jar (Pampore Grade A1)\n• 1 × 500g Raw Kashmiri Acacia Honey Glass Jar\n• 1 × 250g In-Shell Kashmiri Kagzi Walnuts\n• 1 × Handcrafted Papier-Mâché dry-fruit serving bowl\n• 1 × Personalized calligraphy note on handmade flower-petal paper.`,
    price: 18999,
    mrp: 25000,
    image: '/images/crafts-gifting-box.jpg',
    secondaryImage: '/images/luxury-hamper-jars.png',
    detailImage: '/images/crafts-stoles.jpg',
    textureImage: '/images/saffron-jar-5g.jpg',
    packagingImage: '/images/crafts-gifting-box.jpg',
    additionalImages: [
      '/images/crafts-gifting-box.jpg',
      '/images/luxury-hamper-jars.png',
      '/images/crafts-stoles.jpg',
      '/images/saffron-jar-5g.jpg',
    ],
    sizes: ['Executive Presentation Box (16" × 12" × 5")'],
    colorOptions: [
      { name: 'Heritage Emerald & Gold', hex: '#165B4C' },
      { name: 'Royal Midnight Navy', hex: '#16223B' },
    ],
    material: 'Silk-lined presentation box with verified authentic artisanal items',
    craft: 'Curated Multi-Artisan Assembly',
    warmthRating: 'Heavy (-10°C - 4°C)',
    length: 'Mid',
    occasion: 'Wedding',
    fit: 'Luxury Gift Hamper',
    dimensions: '16" × 12" × 5" (Weight: ~3.2 kg)',
    provenance: {
      origin: 'Curated in Srinagar & Packed at Nutty Tales Noida HQ',
      artisanGroup: 'Collaboration of Valley Weavers, Beekeepers & Farmers',
      craftTradition: 'Heritage Gifting Assembly',
      material: 'Silk-lined presentation box with authentic items',
      technique: 'Hand-curated single-origin selection',
      artisanHours: 120,
      giTagCertified: true,
      giCertificateNo: 'NT-HERITAGE-GIFT-2026',
      care: 'Store in a cool dry place. Dry clean stole.',
    },
    isNew: true,
    isBestseller: true,
    isFallWinter2026: true,
    is3DSupported: true,
    tryWithSiSupported: false,
    stockStatus: 'IN_STOCK',
    stockCount: 7,
    tags: ['hamper', 'gifting', 'kashmir-heritage', 'corporate-gifting', 'luxury', 'fw26'],
    reviews: [
      {
        id: 'rev-023',
        author: 'Vivek Singhal',
        city: 'New Delhi',
        rating: 5,
        date: 'Oct 6, 2026',
        comment: 'Sent this to our international board members. They were completely blown away by the craftsmanship and the saffron.',
        verifiedPurchase: true,
      },
    ],
  },
]

// ─── PRIMARY CLOTHING NAVIGATION CONFIGURATION ──────────────────────────────────
export const PRIMARY_CLOTHING_NAV = [
  { slug: 'women', label: 'WOMEN', href: '/crafts/women' },
  { slug: 'men', label: 'MEN', href: '/crafts/men' },
  { slug: 'kids', label: 'KIDS', href: '/crafts/kids' },
  { slug: 'shawls-stoles', label: 'SHAWLS & STOLES', href: '/crafts/shawls-stoles' },
  { slug: 'pherans', label: 'PHERANS', href: '/crafts/pherans' },
  { slug: 'jackets-coats', label: 'JACKETS & COATS', href: '/crafts/jackets-coats' },
  { slug: 'winter-wear', label: 'WINTER WEAR', href: '/crafts/winter-wear' },
  { slug: 'accessories', label: 'ACCESSORIES', href: '/crafts/accessories' },
  { slug: 'heritage-home', label: 'HERITAGE HOME', href: '/crafts/heritage-home' },
] as const

// ─── SECONDARY SEASONAL COLLECTIONS CONFIGURATION ───────────────────────────────
export const SECONDARY_COLLECTIONS = [
  { id: 'new-arrivals', label: 'NEW ARRIVALS' },
  { id: 'fall-winter-2026', label: 'FALL / WINTER 2026' },
  { id: 'bestsellers', label: 'BESTSELLERS' },
  { id: 'craft-collection', label: 'CRAFT COLLECTION' },
  { id: 'gifting', label: 'GIFTING' },
] as const

// ─── CATEGORY TILES CONFIGURATION (PRODUCT-FOCUSED, NO MODELS) ─────────────────
export const PRODUCT_CATEGORY_TILES = [
  {
    slug: 'pherans',
    label: 'Pherans',
    sub: 'Tweed · Velvet · Tilla · Aari',
    desc: 'Garment close-up & folded traditional silhouettes',
    image: '/images/crafts-pherans.jpg',
    href: '/crafts/pherans',
  },
  {
    slug: 'shawls-stoles',
    label: 'Shawls & Stoles',
    sub: 'Pashmina · Kani · Sozni',
    desc: 'Loom drape, fine weave & heritage embroidery',
    image: '/images/crafts-shawls.jpg',
    href: '/crafts/shawls-stoles',
  },
  {
    slug: 'jackets-coats',
    label: 'Jackets & Coats',
    sub: 'Tweed Overcoats · Velvet · Nehru',
    desc: 'Structured hanging outerwear & tailored trims',
    image: '/images/crafts-jackets.jpg',
    href: '/crafts/jackets-coats',
  },
  {
    slug: 'stoles',
    label: 'Stoles & Scarves',
    sub: 'Rolled & Folded Pure Wool',
    desc: 'Compact everyday winter wraps',
    image: '/images/crafts-stoles.jpg',
    href: '/crafts/shawls-stoles',
  },
  {
    slug: 'winter-wear',
    label: 'Winter Wear',
    sub: 'Capes · Ponchos · Co-ords',
    desc: 'Sweepers, knitwear & warm mountain layers',
    image: '/images/crafts-winterwear.jpg',
    href: '/crafts/winter-wear',
  },
  {
    slug: 'accessories',
    label: 'Accessories',
    sub: 'Mufflers · Gloves · Caps',
    desc: 'Studio flat lay of winter accessories',
    image: '/images/crafts-accessories.jpg',
    href: '/crafts/accessories',
  },
] as const

// ─── FILTER METADATA ────────────────────────────────────────────────────────────
export const AVAILABLE_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Free Size', '38', '40', '42', '44', '46']
export const AVAILABLE_COLOURS = [
  { name: 'Burgundy', hex: '#631B26' },
  { name: 'Forest Green', hex: '#165B4C' },
  { name: 'Navy', hex: '#16223B' },
  { name: 'Camel', hex: '#C19A6B' },
  { name: 'Warm Ivory', hex: '#FAF5E8' },
  { name: 'Rust Clay', hex: '#A34828' },
  { name: 'Charcoal Grey', hex: '#373A3C' },
  { name: 'Deep Teal', hex: '#1E585E' },
  { name: 'Onyx Black', hex: '#1A1A1A' },
]
export const AVAILABLE_MATERIALS = [
  'Pure Wool',
  'Wool Blend',
  'Silk Velvet',
  'Cashmilon',
  'Certified Pashmina',
  'Merino Wool',
  'Cashmere Blend',
]
export const AVAILABLE_CRAFTS = [
  'Aari',
  'Sozni',
  'Tilla / Zari',
  'Kani Weave',
  'Handloom Tweed',
  'Walnut Carving',
  'Papier-Mâché',
]
export const AVAILABLE_OCCASIONS = ['Everyday', 'Office', 'Festive', 'Wedding', 'Luxury']
export const AVAILABLE_WARMTHS = ['Light (12°C - 20°C)', 'Medium (4°C - 12°C)', 'Heavy (-10°C - 4°C)']

// ─── QUERY & HELPER FUNCTIONS ──────────────────────────────────────────────────
export function getAllClothing(): ClothingProduct[] {
  return CLOTHING_PRODUCTS
}

export function getClothingBySlug(slug: string): ClothingProduct | undefined {
  return CLOTHING_PRODUCTS.find((p) => p.slug === slug)
}

export function getClothingByGender(gender: ClothingGender): ClothingProduct[] {
  return CLOTHING_PRODUCTS.filter((p) => p.gender === gender || p.gender === 'unisex')
}

export function getClothingByCategory(category: PrimaryClothingCategory): ClothingProduct[] {
  return CLOTHING_PRODUCTS.filter(
    (p) => p.primaryCategory === category || (category === 'women' && p.gender === 'women') || (category === 'men' && p.gender === 'men')
  )
}

export function getNewArrivals(): ClothingProduct[] {
  return CLOTHING_PRODUCTS.filter((p) => p.isNew)
}

export function getBestsellers(): ClothingProduct[] {
  return CLOTHING_PRODUCTS.filter((p) => p.isBestseller)
}

export function getFallWinter2026(): ClothingProduct[] {
  return CLOTHING_PRODUCTS.filter((p) => p.isFallWinter2026)
}

export function get3DInspectableClothing(): ClothingProduct[] {
  return CLOTHING_PRODUCTS.filter((p) => p.is3DSupported)
}

export function getTryWithSiClothing(): ClothingProduct[] {
  return CLOTHING_PRODUCTS.filter((p) => p.tryWithSiSupported)
}
